In [3]:
import numpy as np

a =    np.arange(0,9).reshape(3,3)
print("3x3 matrix \n",a)
b = a[::2,1::2]
print("odd and even numbers\n ",b)
c = 3*a
print("Multiplying\n",c)
d = np.identity((3),dtype = int)
print("Adding with identity matrix\n",c+d)

3x3 matrix 
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
odd and even numbers
  [[1]
 [7]]
Multiplying
 [[ 0  3  6]
 [ 9 12 15]
 [18 21 24]]
Adding with identity matrix
 [[ 1  3  6]
 [ 9 13 15]
 [18 21 25]]
